### ISSUE TITLE
Will valip gain some love?

### ISSUE THREAD

**Issue by mynomoto** [weavejester/valip#5]
Hi James, will you maintain valip?

I found https://groups.google.com/d/msg/clojure/Bp0pKvPPZ-A/fq1E24t5MBQJ and think it would be great. And I love the syntax.

**Comment by weavejester** [comment]
Valip is, unfortunately, pretty far down on my todo list. I don't have any immediate plans to update it. However, you're welcome to take the source, or use one of the other validation libraries. [The Clojure Toolbox](http://www.clojure-toolbox.com) lists quite a few.

**Comment by mynomoto** [comment]
Thanks for answering this. Other day I added valip to the Toolbox (your version), but I think that in this moment cemerick's version is working better. May I change the valip url in the toolbox?

And, if I may ask, since I usually like your choices (and libraries), what are you using to validation?

Lastly, should I close this or leave it here for warning other users?
